### ISSUE TITLE
Error on `bin/build_s5`

### ISSUE THREAD

**Issue by brannerchinese** [cewing/training.python_web#96]
I have cloned your Python web training project, but at the step `bin/build_s5` I run into an error:

    (v_env2)$ bin/build_s5 
    bin/build_s5: line 13: /Users/.../training.python_web/bin/rst2s5.py: No such file or directory
    ... 
    (v_env2)$ 

The message repeats about a dozen times. I see the a file by this name (`rst2s5.py`) at `/Users/.../training.python_web/eggs/docutils-0.11-py2.7.egg/EGG-INFO/scripts/rst2s5.py`, and copying it to the path specified in `build_s5:13` seems to solve the problem. But I thought you should know about this surprise during building.

In `build/sphynx` there had been one warning:

    copying static files... WARNING: html_static_path entry '/Users/.../training.python_web/source/main/_static' does not exist

Perhaps related? I haven't investigated, but will be glad to answer any questions about my configuration here if you like. I'm on Mac OS 10.9.3, and I've installed with Python 2.7.5 and pip 1.5.4.

Thanks for going to the trouble to post what promises to be a very helpful set of training materials.

**Comment by cewing** [comment]
FYI, @brannerchinese, I have re-made the build system for this project.  I will close this issue when I've re-written the README to correctly reflect the current instructions.  

Thanks for your bug report.

**Comment by cewing** [comment]
the new build system is documented and works properly, afaict.  I'm going to close this as no longer relevant.
