### ISSUE TITLE
Some places the title for the slide does not show up in the html version

### ISSUE THREAD

**Issue by codedragon** [cewing/training.python_web#99]
So students can't tell which file they should be editing. After this line:
Open learning_journal/forms.py and add the following:
are two edits, and it isn't clear what file the second is for.

Some students may also be not clear on what file this edit is for (after this line):
Now we have to update our template to display the form, if it is there

And in that block of code, there is an else that should be endif:
</form></aside>
{% else %}
{% if entries %}

**Comment by cewing** [comment]
Fixed by b4f4ab6

thanks for the report, @codedragon
